kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - namespace.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - configmap.yaml
  - daemonset.yaml
  - deployment.yaml
  - job.yaml
  - mutationwebhookconfiguration.yaml
  - service.yaml
  - serviceaccount.yaml
  - statefulset.yaml
  - secret.yaml
  - role.yaml
  - rolebinding.yaml

patches:
  - target:
      kind: ClusterRole
      name: nri-bundle-nri-metadata-injection-admission
    patch: |
      - op: remove
        path: /metadata/annotations/helm.sh/hook: pre-install,pre-upgrade,post-install,post-upgrade
      - op: remove
        path: /metadata/annotations/helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
      